name: laravelapp

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8081:80'
    volumes:
      - ./src:/var/www/html
      - ./myngnix/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated # delegated is used for performance

  mysql:
    image: mysql
    restart: always
    env_file:
      - ./env/mysql.env

  composer:
    container_name: composer
    build:
      context: .
      dockerfile: dockerfiles/composer.dockerfile
    volumes:
      - ./src:/var/www/html

  artisan:
    container_name: artisan
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

  npm:
    container_name: npm
    image: node
    working_dir: /var/www/html
    entrypoint: ["npm"]
    expose:
      - 5173
    ports:
      - '5173:5173'
    volumes:
      - ./src:/var/www/html
